function(pgp_add_compile_flag flag)
    include(CheckCXXCompilerFlag)
    CHECK_CXX_COMPILER_FLAG(${flag} COMPILER_SUPPORTS_${flag})
    if (COMPILER_SUPPORTS_${flag})
        set(PGP_DEFAULT_CXX_FLAGS "${PGP_DEFAULT_CXX_FLAGS} ${flag}" PARENT_SCOPE)
    else ()
        message(WARNING "Compiler doesn't support flag ${flag}")
    endif ()
endfunction()