[package]
name = "ods-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "bin/usage.rs"
name = "uasge"

[[bin]]
path = "bin/temp.rs"
name = "temp"

[[bin]]
path = "bin/ch1/ex11.rs"
name = "ex11"


[dependencies]
